image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install uv
    init: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc

vscode:
  extensions:
    - ms-python.python